[acoustics]
sr = 16000
n_fft = 512
win_length = 512
hop_length = 256

[inferencer]
path = "inferencer.Inferencer"
type = "full_band_crm_mask"

[dataset]
path = "dataset_inference.Dataset"

[model]
path = "fullsubnet.model.Model"

[inferencer.args]
n_neighbor = 15

[dataset.args]
dataset_dir_list = [ "enhancement/noisy",]
sr = 16000

[model.args]
sb_num_neighbors = 15
fb_num_neighbors = 0
num_freqs = 257
look_ahead = 2
sequence_model = "LSTM"
fb_output_activate_function = "ReLU"
sb_output_activate_function = false
fb_model_hidden_size = 512
sb_model_hidden_size = 384
weight_init = false
norm_type = "offline_laplace_norm"
num_groups_in_drop_band = 2
