#python inference.py \
#  -C fullsubnet/inference.toml \
#  -M /path/to/your/checkpoint_dir/best_model.tar \
#  -O /path/to/your/enhancement/dir

# run inference with 
# CUDA_VISIBLE_DEVICES=0 python inference.py -C fullsubnet/inference.toml -M /home/benedikt/thesis/repos/FullSubNet/FullSubNet_TRY_14_06_21_DENOISE/train_16k_buf/checkpoints/best_model.tar -O ~/Experiments/FullSubNet/Denoise_21_06_14/inference
# CUDA_VISIBLE_DEVICES="" python inference.py -C fullsubnet/inference.toml -M /home/benedikt/Experiments/FullSubNet/Dereverb_21_06_28/train_16k_buf/checkpoints/best_model.tar -O /home/benedikt/Experiments/FullSubNet/Dereverb_21_06_28/inference

[config_replacement]
m_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/baseline/2021_7_10/train_BGM_baseline/checkpoints/best_model.tar"
o_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/baseline/2021_7_10/train_BGM_baseline/baseline_plain_inference"


[acoustics]
sr = 16000
n_fft = 512
win_length = 512
hop_length = 256


[inferencer]
path = "inferencer.Inferencer"
type = "full_band_crm_mask"
[inferencer.args]


[dataset]
path = "audio_zen.dataset.parallel_dataset.Dataset"

[dataset.args]
dataset_dir_list = [
    "/home/benedikt/thesis/TRAIN_EVALUATION_DATA/LEAKAGE_REMOVAL/LEAKAGE_REMOVAL_2021_7_15/TEST_SET_CONV",
    "/home/benedikt/thesis/TRAIN_EVALUATION_DATA/LEAKAGE_REMOVAL/LEAKAGE_REMOVAL_2021_7_15/TEST_SET_ALIGNED_LONG_CONV",
    "/home/benedikt/thesis/TRAIN_EVALUATION_DATA/LEAKAGE_REMOVAL/LEAKAGE_REMOVAL_2021_7_15/TEST_SET_UNALIGNED_LONG_CONV",
    "/home/benedikt/thesis/TRAIN_EVALUATION_DATA/LEAKAGE_REMOVAL/LEAKAGE_REMOVAL_2021_7_15/TEST_SET_FOR_HUMAN_ALIGNED",
    "/home/benedikt/thesis/TRAIN_EVALUATION_DATA/LEAKAGE_REMOVAL/LEAKAGE_REMOVAL_2021_7_15/TEST_SET_FOR_HUMAN_UNALIGNED"
]
sr = 16000
limit = 400
target_task = "BGMI_INFERENCE_PLAIN"

[model]
path = "fullsubnet.model.Model"

[model.args]
sb_num_neighbors = 15
fb_num_neighbors = 0
num_freqs = 257
look_ahead = 2
sequence_model = "LSTM"
fb_output_activate_function = "ReLU"
sb_output_activate_function = false
fb_model_hidden_size = 512
sb_model_hidden_size = 384
weight_init = false
norm_type = "offline_laplace_norm"
num_groups_in_drop_band = 2

