#python inference.py \
#  -C fullsubnet/inference.toml \
#  -M /path/to/your/checkpoint_dir/best_model.tar \
#  -O /path/to/your/enhancement/dir

# run inference with 
# CUDA_VISIBLE_DEVICES=0 python inference.py -C fullsubnet/inference.toml -M /home/benedikt/thesis/repos/FullSubNet/FullSubNet_TRY_14_06_21_DENOISE/train_16k_buf/checkpoints/best_model.tar -O ~/Experiments/FullSubNet/Denoise_21_06_14/inference
# CUDA_VISIBLE_DEVICES="" python inference.py -C fullsubnet/inference.toml -M /home/benedikt/Experiments/FullSubNet/Dereverb_21_06_28/train_16k_buf/checkpoints/best_model.tar -O /home/benedikt/Experiments/FullSubNet/Dereverb_21_06_28/inference

[acoustics]
sr = 16000
n_fft = 512
win_length = 512
hop_length = 256


[inferencer]
path = "inferencer.Inferencer"
type = "full_band_crm_mask_BGMI"

[inferencer.args]

[dataset]
path = "audio_zen.dataset.parallel_dataset.Dataset"

[dataset.args]
dataset_dir_list = [
    "/home/benedikt/thesis/TRAIN_EVALUATION_DATA/LEAKAGE_REMOVAL/LEAKAGE_REMOVAL_2021_7_15/TEST_SET_CONV",
    "/home/benedikt/thesis/TRAIN_EVALUATION_DATA/LEAKAGE_REMOVAL/LEAKAGE_REMOVAL_2021_7_15/TEST_SET_ALIGNED_LONG_CONV",
    "/home/benedikt/thesis/TRAIN_EVALUATION_DATA/LEAKAGE_REMOVAL/LEAKAGE_REMOVAL_2021_7_15/TEST_SET_UNALIGNED_LONG_CONV",
    "/home/benedikt/thesis/TRAIN_EVALUATION_DATA/LEAKAGE_REMOVAL/LEAKAGE_REMOVAL_2021_7_15/TEST_SET_FOR_HUMAN_ALIGNED",
    "/home/benedikt/thesis/TRAIN_EVALUATION_DATA/LEAKAGE_REMOVAL/LEAKAGE_REMOVAL_2021_7_15/TEST_SET_FOR_HUMAN_UNALIGNED"

]
sr = 16000
limit = 400
target_task = "BGMI_INFERENCE"


# args for fsn_basic_split -> experiment train_BGM_basic_split
# [config_replacement]
# m_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/2021_7_15/train_BGM_basic_split/checkpoints/best_model.tar"
# o_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/2021_7_15/train_BGM_basic_split/fsn_basic_split_inference"
# [model]
# path = "fullsubnet_aec.fsn_basic_split_model.Model"
# [model.args]
# sb_num_neighbors = 15
# fb_num_neighbors = 0
# num_freqs = 257
# look_ahead = 2
# sequence_model = "LSTM"
# fb_output_activate_function = "ReLU"
# sb_output_activate_function = false
# fb_model_hidden_size = 512
# sb_model_hidden_size = 384
# weight_init = false
# norm_type = "offline_laplace_norm"
# num_groups_in_drop_band = 2

# informed_fullband_baseline
# [config_replacement]
# m_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/informed_fullband_baseline_2021_7_18/train_BGM_informed_fullband_baseline/checkpoints/best_model.tar"
# o_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/informed_fullband_baseline_2021_7_18/train_BGM_informed_fullband_baseline/BGM_informed_fullband_baseline_inference"
# [model]
# path = "fullsubnet_aec.fsn_informed_fullband_baseline.Model"
# [model.args]
# num_freqs = 257
# look_ahead = 2
# sequence_model = "LSTM"
# fb_output_activate_function = "ReLU"
# fb_model_hidden_size = 512
# weight_init = false
# norm_type = "offline_laplace_norm"
# num_groups_in_drop_band = 1


# fsn_subsub_split
# [config_replacement]
# m_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/subsub_split_2021_7_17/train_BGM_subsub_split/checkpoints/best_model.tar"
# o_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/subsub_split_2021_7_17/train_BGM_subsub_split/BGM_subsub_split_inference"
# [model]
# path = "fullsubnet_aec.fsn_subsub_split_model.Model"
# [model.args]
# sb_num_neighbors = 15
# fb_num_neighbors = 15
# num_freqs = 257
# look_ahead = 2
# sequence_model = "LSTM"
# fb_output_activate_function = "ReLU"
# sb_output_activate_function = false
# fb_model_hidden_size = 256
# sb_model_hidden_size = 384
# weight_init = false
# norm_type = "offline_laplace_norm"
# num_groups_in_drop_band = 2

# fsn_subband_baseline
# [config_replacement]
# m_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/informed_subband_baseline_2021_7_29/train_BGM_informed_subband_baseline/checkpoints/best_model.tar"
# o_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/informed_subband_baseline_2021_7_29/train_BGM_informed_subband_baseline/BGM_informed_subband_baseline_inference"

# [model]
# path = "fullsubnet_aec.fsn_informed_subband_baseline.Model"

# [model.args]
# sb_num_neighbors = 15
# num_freqs = 257
# look_ahead = 2
# sequence_model = "LSTM"
# sb_output_activate_function = false
# sb_model_hidden_size = 384
# norm_type = "offline_laplace_norm"
# num_groups_in_drop_band = 2

# fsn_full_dual_baseline
# [config_replacement]
# m_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/full_dual_2021_7_20/train_BGM_full_dual/checkpoints/best_model.tar"
# o_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/full_dual_2021_7_20/train_BGM_full_dual/BGM_full_dual_inference"


# [model]
# path = "fullsubnet_aec.fsn_full_dual_model.Model"

# [model.args]
# sb_num_neighbors = 15
# fb_num_neighbors = 0
# num_freqs = 257
# look_ahead = 2
# sequence_model = "LSTM"
# fb_output_activate_function = "ReLU"
# sb_output_activate_function = false
# fb_model_hidden_size = 512
# sb_model_hidden_size = 384
# weight_init = false
# norm_type = "offline_laplace_norm"
# num_groups_in_drop_band = 2

# fsn_full_dual_baseline_old
[config_replacement]
m_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/full_dual_2021_7_20/train_BGM_full_dual_old/checkpoints/best_model.tar"
o_flag = "/home/benedikt/Experiments/LEAKAGE_REMOVAL/fsn_basic_split/full_dual_2021_7_20/train_BGM_full_dual_old/BGM_full_dual_inference"


[model]
path = "fullsubnet_aec.fsn_full_dual_model.Model"

[model.args]
sb_num_neighbors = 15
fb_num_neighbors = 0
num_freqs = 257
look_ahead = 2
sequence_model = "LSTM"
fb_output_activate_function = "ReLU"
sb_output_activate_function = false
fb_model_hidden_size = 512
sb_model_hidden_size = 384
weight_init = false
norm_type = "offline_laplace_norm"
num_groups_in_drop_band = 2