inherit = "config/common/fullband_train.toml"

[meta]
save_dir = "~/Experiments/Fullband"
use_amp = true

[model]
path = "model.fullband_model.Model"
[model.args]
use_offline_laplace_norm = true

[train_dataset.dataloader]
batch_size = 80  # for V100 32GB, may be you need to reduce the value.
num_workers = 6
shuffle = true


[trainer]
path = "trainer.fullband_trainer.Trainer"
[trainer.train]
epochs = 5000
save_checkpoint_interval = 1
[trainer.validation]
validation_interval = 1
[trainer.visualization]
n_samples = 20
num_workers = 8
metrics = ["WB_PESQ", "NB_PESQ", "STOI", "SI_SDR"]
